# Generated by Django 5.0.1 on 2025-02-17 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.TextField(blank=True, max_length=200, null=True)),
                ('booking_id', models.AutoField(primary_key=True, serialize=False)),
                ('client_id', models.IntegerField(blank=True, null=True)),
                ('room_id', models.IntegerField(blank=True, null=True)),
                ('check_in_date', models.DateField(max_length=200)),
                ('check_out_date', models.DateField(max_length=200)),
                ('number_of_guests', models.IntegerField(blank=True, null=True)),
                ('total_price', models.FloatField(blank=True, max_length=200, null=True)),
                ('booking_status', models.TextField(max_length=200)),
            ],
            options={
                'db_table': 'Booking',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.TextField(blank=True, max_length=200, null=True)),
                ('client_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(blank=True, max_length=200, null=True)),
                ('last_name', models.CharField(blank=True, max_length=200, null=True)),
                ('contact', models.IntegerField()),
                ('id_no', models.IntegerField(unique=True)),
                ('email', models.CharField(blank=True, max_length=200, null=True)),
                ('gender', models.TextField(max_length=200)),
                ('password', models.CharField(blank=True, max_length=200, null=True)),
                ('code', models.IntegerField(unique=True)),
            ],
            options={
                'db_table': 'Client',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.TextField(blank=True, max_length=200, null=True)),
                ('inventory_id', models.AutoField(primary_key=True, serialize=False)),
                ('item_name', models.CharField(blank=True, max_length=200, null=True)),
                ('category', models.CharField(blank=True, max_length=200, null=True)),
                ('item_description', models.TextField(blank=True, max_length=200, null=True)),
                ('quantity', models.IntegerField(blank=True, null=True)),
                ('price_per_unit', models.FloatField(blank=True, max_length=200, null=True)),
            ],
            options={
                'db_table': 'Inventory',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.TextField(blank=True, max_length=200, null=True)),
                ('payment_id', models.AutoField(primary_key=True, serialize=False)),
                ('booking_id', models.IntegerField(blank=True, null=True)),
                ('service_id', models.IntegerField(blank=True, null=True)),
                ('amount', models.FloatField(blank=True, max_length=200, null=True)),
                ('payment_date', models.DateField(blank=True, max_length=200, null=True)),
                ('payment_mode', models.TextField(max_length=200)),
                ('account', models.IntegerField()),
                ('payment_status', models.TextField(max_length=200)),
            ],
            options={
                'db_table': 'payment',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.TextField(blank=True, max_length=200, null=True)),
                ('room_id', models.AutoField(primary_key=True, serialize=False)),
                ('room_type', models.CharField(max_length=200)),
                ('bed_type', models.CharField(max_length=200)),
                ('price_per_night', models.FloatField(max_length=200)),
                ('availabilty_status', models.IntegerField()),
                ('max_occupation', models.IntegerField()),
            ],
            options={
                'db_table': 'Room',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.TextField(blank=True, max_length=200, null=True)),
                ('service_id', models.AutoField(primary_key=True, serialize=False)),
                ('service_name', models.CharField(max_length=200)),
                ('service_description', models.TextField(blank=True, max_length=200, null=True)),
                ('service_price', models.FloatField(blank=True, max_length=200, null=True)),
            ],
            options={
                'db_table': 'Service',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ServiceRequest',
            fields=[
                ('id', models.TextField(blank=True, max_length=200, null=True)),
                ('request_id', models.AutoField(primary_key=True, serialize=False)),
                ('booking_id', models.IntegerField(blank=True, null=True)),
                ('service_id', models.IntegerField(blank=True, null=True)),
                ('request_date', models.DateField(blank=True, max_length=200, null=True)),
                ('request_status', models.TextField()),
            ],
            options={
                'db_table': 'Service_request',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.TextField(blank=True, max_length=200, null=True)),
                ('staff_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(blank=True, max_length=200, null=True)),
                ('last_name', models.CharField(blank=True, max_length=200, null=True)),
                ('contact', models.IntegerField()),
                ('id_no', models.IntegerField(unique=True)),
                ('email', models.CharField(blank=True, max_length=200, null=True)),
                ('role', models.CharField(blank=True, max_length=200, null=True)),
                ('salary', models.IntegerField()),
                ('date_of_joining', models.DateField(max_length=200)),
                ('shift_start', models.TimeField(max_length=200)),
                ('shift_end', models.TimeField(max_length=200)),
                ('gender', models.TextField(max_length=200)),
                ('password', models.CharField(blank=True, max_length=200, null=True)),
                ('code', models.IntegerField(unique=True)),
            ],
            options={
                'db_table': 'Staff',
                'managed': False,
            },
        ),
    ]
